baseurl = "https://computingbiology.github.io/s22/"
languageCode = "en-us"
title = "Computational Biology / Biological Computing"
subtitle = "UVA CS 4501 Spring 2022 [Archive]"
copyright = ""
theme = "biocs"

paginate = 10
paginatePath = "page"

pageNotFoundTitle = "Not Found"
pageNotFoundDetail = "Your request does not correspond to any known life form. This could be because you have discovered a novel path-ogen, but it is most likely a bad link or mistyped URL. If its a broken link, please let us know."

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    post = "/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "David Evans"
    email = "evans@virginia.edu"

[params]
    brand = "Computational Biology / Biological Computing"
    topline = "Computational Biology / Biological Computing"
    footline = "<p align=\"center\">CS 4501 | University of Virginia, Spring 2022 [Archive] | <a href=\"https://www.cs.virginia.edu/evans\">David Evans</a></p>"
    sidebar = "left"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[[menu.footer]]
